defaults: &defaults
  facebook:
    app_id: <%= ENV['FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  google:
    youtube:
      api_key: <%= ENV['YOUTUBE_API_KEY'] %>
  vietnamese_stopwords: [bị, các, chiếc, của, cũng, đã, để, đến, được, khi, khiến, là, như, những, 
                        ngay, ở, sau, sẽ, tại, trên, trong, và, vào, vì, với]

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults