defaults: &defaults
  facebook:
    app_id: <%= ENV['FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  google:
    youtube:
      api_key: <%= ENV['YOUTUBE_API_KEY'] %>

development:
  <<: *defaults